Repository wecode-bootcamp-korea/35-1st-LocTea-frontend, pull requests merged in 2022-07, with the labels that each got.

#9 메인 폰트, 로고 이미지, favicon 추가 (master에 merge 필요)
  public/images/Footer/LocTea.png
  public/images/favicon.ico
  public/index.html
  src/styles/common.scss
Labels: 멘토 리뷰 요청, 완료

#10 Add: common.scss 추가 (merge 필요)
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#4 [김익현] 록차 상품 상세 페이지 3차 리뷰사항 수정완료 & 백엔드 통신완료.
  public/data/itemData.json
  public/index.html
  src/Router.js
  src/pages/ItemDetail/ItemDetail.js
  src/pages/ItemDetail/ItemDetail.scss
Labels: 멘토 리뷰 요청, 완료

#17 [류승연] Footer 완료
  public/images/Footer/applePay.png
  public/images/Footer/consult.png
  public/images/Footer/ex.js
  public/images/Footer/faq.png
  public/images/Footer/location.png
  public/images/Footer/market.png
  public/images/Footer/points.png
  public/images/Footer/up-arrow.png
  src/Components/Footer/BtnForUp.js
  src/Components/Footer/BtnForUp.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/FooterData.js
  src/Components/Footer/FooterSnsData.js
  src/Components/Footer/FooterUtilData.js
  src/Router.js
  src/styles/variable.scss
Labels: 완료

#5 [이금관]register& login 병합 + 통신 완료
  public/images/login/Kakao.png
  public/images/login/LocTea.png
  public/images/login/more.png
  public/images/login/naver.png
  public/images/login/phone.png
  src/Components/Nav/Nav.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/Sns.js
  src/pages/Login/SnsData.js
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
Labels: 멘토 리뷰 요청

#20 add: router Nav&Footer 회원가입&로그인에서 숨김 (Merge 필요)
  src/Router.js
Labels: 멘토 리뷰 요청

#13 [이금관] Feature/nav 로그인 시 nav바 상태 바뀌는것 구현 할 예정
  public/data/NavItemType.json
  src/Components/Nav/ItemType.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/WithNav.js
  src/pages/Cart/Cart.js
Labels: 멘토 리뷰 요청

#23 register 글씨체 변경 merge 필요
  src/pages/Login/Login.scss
  src/pages/Register/Register.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#24 Feature/nav [로그인 상태에서 Nav 상태 변경] [merge 필요]
  src/Components/Nav/ItemType.js
  src/Components/Nav/Nav.js
  src/Router.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Register/Register.js
Labels: 멘토 리뷰 요청

#21 [김익현] 록차 상세페이지 장바구니 통신완료(바로구매탭 통신예정)
  public/data/itemData.json
  src/Router.js
  src/pages/ItemDetail/ItemDetail.js
  src/pages/ItemDetail/ItemDetail.scss
  src/pages/Main/Main.js
Labels: 추가 기능 구현 중

#19 [김익현] 록차 주문서 페이지 구현완료(백엔드 데이터 확인해보겠습니다!)
  public/data/purchaseData.json
  public/index.html
  src/Components/Footer/Footer.scss
  src/Router.js
  src/pages/Purchase/Purchase.js
  src/pages/Purchase/Purchase.scss
Labels: Conflict 해결 요청

#11 [김익현]록차 메인 중단페이지 공지사항,베스트메뉴 슬라이드바,타임세일
  public/data/summerData.json
  public/data/weekBest.json
  src/pages/Main/HotTea/HotTea.js
  src/pages/Main/HotTea/HotTea.scss
  src/pages/Main/Main.js
  src/pages/Main/Notice/Notice.js
  src/pages/Main/Notice/Notice.scss
  src/pages/Main/Subscribe/Subscribe.js
  src/pages/Main/Subscribe/Subscribe.scss
  src/pages/Main/TimeSale/TimeSale.js
  src/pages/Main/TimeSale/TimeSale.scss
Labels: Conflict 해결 요청
